// <auto-generated />
using System;
using Meal_Planner_Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Meal_Planner_Api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Meal_Planner_Api.Models.Amount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Amounts", (string)null);
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.CookingTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Minutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CookingTimes", (string)null);
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AmountId");

                    b.HasIndex("UnitId");

                    b.ToTable("Ingredients", (string)null);
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.Instruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Instructions", (string)null);
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.PreparationTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Minutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PreparationTimes", (string)null);
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Ratings", (string)null);
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecipeScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RecipeScheduleId");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes", (string)null);
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.RecipeCookingTime", b =>
                {
                    b.Property<int>("RecipeID")
                        .HasColumnType("int");

                    b.Property<int>("CookingTimeID")
                        .HasColumnType("int");

                    b.HasKey("RecipeID", "CookingTimeID");

                    b.HasIndex("CookingTimeID");

                    b.ToTable("RecipeCookingTimes", (string)null);
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeID")
                        .HasColumnType("int");

                    b.Property<int>("IngredientID")
                        .HasColumnType("int");

                    b.HasKey("RecipeID", "IngredientID");

                    b.HasIndex("IngredientID");

                    b.ToTable("RecipeIngredients", (string)null);
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.RecipePreparationTime", b =>
                {
                    b.Property<int>("RecipeID")
                        .HasColumnType("int");

                    b.Property<int>("PreparationTimeID")
                        .HasColumnType("int");

                    b.HasKey("RecipeID", "PreparationTimeID");

                    b.HasIndex("PreparationTimeID");

                    b.ToTable("RecipePreparationTimes", (string)null);
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.RecipeRating", b =>
                {
                    b.Property<int>("RecipeID")
                        .HasColumnType("int");

                    b.Property<int>("RatingID")
                        .HasColumnType("int");

                    b.HasKey("RecipeID", "RatingID");

                    b.HasIndex("RatingID");

                    b.ToTable("RecipeRatings", (string)null);
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.RecipeSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Column")
                        .HasColumnType("int");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RecipeSchedules", (string)null);
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.RecipeServings", b =>
                {
                    b.Property<int>("RecipeID")
                        .HasColumnType("int");

                    b.Property<int>("ServingID")
                        .HasColumnType("int");

                    b.HasKey("RecipeID", "ServingID");

                    b.HasIndex("ServingID");

                    b.ToTable("RecipeServings", (string)null);
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.Servings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Servings", (string)null);
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Measurement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Units", (string)null);
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.UserRating", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RatingId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RatingId");

                    b.HasIndex("RatingId");

                    b.ToTable("UserRating", (string)null);
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.Ingredient", b =>
                {
                    b.HasOne("Meal_Planner_Api.Models.Amount", "Amount")
                        .WithMany("Ingredients")
                        .HasForeignKey("AmountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meal_Planner_Api.Models.Unit", "Unit")
                        .WithMany("Ingredients")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amount");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.Instruction", b =>
                {
                    b.HasOne("Meal_Planner_Api.Models.Recipe", "Recipe")
                        .WithMany("Instructions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.Recipe", b =>
                {
                    b.HasOne("Meal_Planner_Api.Models.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meal_Planner_Api.Models.RecipeSchedule", null)
                        .WithMany("Recipes")
                        .HasForeignKey("RecipeScheduleId");

                    b.HasOne("Meal_Planner_Api.Models.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.RecipeCookingTime", b =>
                {
                    b.HasOne("Meal_Planner_Api.Models.CookingTime", "CookingTime")
                        .WithMany("RecipeCookingTime")
                        .HasForeignKey("CookingTimeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meal_Planner_Api.Models.Recipe", "Recipe")
                        .WithMany("RecipeCookingTime")
                        .HasForeignKey("RecipeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CookingTime");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.RecipeIngredient", b =>
                {
                    b.HasOne("Meal_Planner_Api.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meal_Planner_Api.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.RecipePreparationTime", b =>
                {
                    b.HasOne("Meal_Planner_Api.Models.PreparationTime", "PreparationTime")
                        .WithMany("RecipePreparationTime")
                        .HasForeignKey("PreparationTimeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meal_Planner_Api.Models.Recipe", "Recipe")
                        .WithMany("RecipePreparationTime")
                        .HasForeignKey("RecipeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreparationTime");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.RecipeRating", b =>
                {
                    b.HasOne("Meal_Planner_Api.Models.Rating", "Rating")
                        .WithMany("RecipeRating")
                        .HasForeignKey("RatingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meal_Planner_Api.Models.Recipe", "Recipe")
                        .WithMany("RecipeRating")
                        .HasForeignKey("RecipeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rating");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.RecipeSchedule", b =>
                {
                    b.HasOne("Meal_Planner_Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.RecipeServings", b =>
                {
                    b.HasOne("Meal_Planner_Api.Models.Recipe", "Recipe")
                        .WithMany("RecipeServings")
                        .HasForeignKey("RecipeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meal_Planner_Api.Models.Servings", "Servings")
                        .WithMany("RecipeServings")
                        .HasForeignKey("ServingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("Servings");
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.UserRating", b =>
                {
                    b.HasOne("Meal_Planner_Api.Models.Rating", "Rating")
                        .WithMany("UserRating")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meal_Planner_Api.Models.User", "User")
                        .WithMany("UserRating")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rating");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.Amount", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.Category", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.CookingTime", b =>
                {
                    b.Navigation("RecipeCookingTime");
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.PreparationTime", b =>
                {
                    b.Navigation("RecipePreparationTime");
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.Rating", b =>
                {
                    b.Navigation("RecipeRating");

                    b.Navigation("UserRating");
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.Recipe", b =>
                {
                    b.Navigation("Instructions");

                    b.Navigation("RecipeCookingTime");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("RecipePreparationTime");

                    b.Navigation("RecipeRating");

                    b.Navigation("RecipeServings");
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.RecipeSchedule", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.Servings", b =>
                {
                    b.Navigation("RecipeServings");
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.Unit", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("Meal_Planner_Api.Models.User", b =>
                {
                    b.Navigation("Recipes");

                    b.Navigation("UserRating");
                });
#pragma warning restore 612, 618
        }
    }
}
